services:
  react-front:
    build:
      context: .
    container_name: react-front
    volumes:
      - ./:/react-app:delegated
      - /node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    networks:
      frontend:

networks:
  frontend:
    name: symfony-docker-main_frontend
    external: true